joint_state_controller:
  # The joint state controller handles publishing transforms for any moving joints
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: joint1
  pid: {p: 100.0, i: 0.01, d: 10.0}
